### ISSUE TITLE
iphone got Hanged

### ISSUE THREAD

**Issue by SandeepAggarwal** [wokalski/AsyncVideoPlayer#1]
I have used this player inside a ASCellNode (AsyncDisplayKit) and it is making my phone unresponsive!.
I need to restart my phone to make other apps work.

**Comment by wokalski** [comment]
Made my day bruh. I don't use this library, neither do I support it.

**Comment by SandeepAggarwal** [comment]
Any idea so that I can look into it and fix it?

**Comment by wokalski** [comment]
no to be honest. If you can't spot it with the debugger, try logging stuff.
